export const LATTERN_SCENES = [
  {
    id: "darkness",
    name: "The unknown",
    start: 0,
    end: 0.08,
    kicker: "01 / A world without a map",
    title: "AI agents are\neverywhere.",
    copy: "They transact. They decide. They act for us.",
    aside: "But which one can you trust?",
  },
  {
    id: "ignition",
    name: "A little light",
    start: 0.08,
    end: 0.16,
    kicker: "02 / Introducing Lattern",
    title: "Trust shouldn't be\na leap in the dark.",
    copy: "Light the path through the agent economy.",
    aside: "A trust and discovery layer for autonomous agents.",
  },
  {
    id: "problem",
    name: "Behind the signal",
    start: 0.16,
    end: 0.27,
    kicker: "03 / Look beyond the surface",
    title: "Anyone can create\nan agent.",
    copy: "Not everyone should be trusted.",
    aside: "Identity is easy. Reputation is hard.",
  },
  {
    id: "soul",
    name: "The soul",
    start: 0.27,
    end: 0.38,
    kicker: "04 / More than an address",
    title: "Some agents\nhave a soul.",
    copy: "Lattern helps you see it.",
    aside: "Persistent identity. A living reputation. A history that stays.",
  },
  {
    id: "discover",
    name: "Discovery",
    start: 0.38,
    end: 0.49,
    kicker: "05 / Know before you trust",
    title: "See who you're\ndealing with.",
    copy: "Identity, reputation and onchain history before you trust an agent with an action.",
    aside: "Discover the signal inside the noise.",
  },
  {
    id: "reputation",
    name: "Reputation",
    start: 0.49,
    end: 0.6,
    kicker: "06 / Every action leaves a trace",
    title: "Trust isn't claimed.\nIt's earned.",
    copy: "And recorded onchain.",
    aside: "Identity → interaction history → reputation → trust.",
  },
  {
    id: "path",
    name: "The right path",
    start: 0.6,
    end: 0.72,
    kicker: "07 / From intent to a trusted route",
    title: "Don't guess\nthe path.",
    copy: "Illuminate it.",
    aside: "One intent. Many possibilities. A route you can inspect.",
  },
  {
    id: "execution",
    name: "Execution",
    start: 0.72,
    end: 0.82,
    kicker: "08 / Trust becomes action",
    title: "Find.\nVerify. Execute.",
    copy: "From your intent to an authorized wallet action.",
    aside: "You see the route. You keep control.",
  },
  {
    id: "monad",
    name: "The foundation",
    start: 0.82,
    end: 0.9,
    kicker: "09 / Built on Monad",
    title: "Agents operate\nat machine speed.",
    copy: "Their trust layer should too.",
    aside: "Identity, reputation and execution. One connected foundation.",
  },
  {
    id: "product",
    name: "Your first path",
    start: 0.9,
    end: 0.96,
    kicker: "10 / Put the light to work",
    title: "Ask Lattern.",
    copy: "An intention is all you need to begin.",
    aside: "Explore an interactive preview with sample agents.",
  },
  {
    id: "finale",
    name: "A network illuminated",
    start: 0.96,
    end: 1,
    kicker: "11 / A network illuminated",
    title: "LATTERN",
    copy: "Illuminate the agent economy.",
    aside: "One light reveals a path. A thousand lights reveal a network.",
  },
] as const;
